GOOGLE_APP_ID: '1025268074439-uvec86odjc8elgipid5jknogo19kgbpp.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'oXiGH6e3VQtccGv1vb0hUSTU'
GOOGLE_RECAPT_SITE_KEY: '6LeoD8MUAAAAAKwNEaSoaUVMDf467ST9OID_tqxc'
GOOGLE_RECAPT_SECRET_KEY: '6LeoD8MUAAAAACSNhrFZFdP_l_YM7ryljWMN2Bo3'
FACEBOOK_APP_ID: '2525672330999747'
FACEBOOK_APP_SECRET: '6783b56bc1382e8d43fcd6ae2b54321e'